### ISSUE TITLE
Fishing doesn't work and has never worked properly

### ISSUE THREAD

**Issue by inthere29** [DiscordDungeons/Bugs#923] opened 2020-03-31 16:49 UTC
**Describe the bug**
Fishing as it is right now, is completely dead. It doesn’t scale like the other skills, for instance; at level 30, the other 3 skills give you 31 base items, while fishing still gives you only the 1 item you got at level one. 

**To Reproduce**
type #!fish 

**Expected behavior**
fishing should scale like the other 3 skills, giving one extra item per skill level. 

**Screenshots**

**Version**
Discord Dungeons version  4.14.3

**Comment by FelixArgyle** [comment] 2020-03-31 16:55
Not a bug, it's an intended feature. 
(In a logical sense leveling up a skill for fishing shouldn't increase how many fish you catch, upgrading tools to stuff like a fishing rod to fishing net etc would increase the amount of fish caught, think of enchanted tools like that)

**Comment by inthere29** [comment] 2020-03-31 17:28
Well as it is now the skill is completely dead and there's no reason for leveling it or putting points into it as a potential moneymaking option, so though it's an intended feature, maybe it's time to change it?

**Comment by inthere29** [comment] 2020-03-31 17:30
thanks for the swift reply!

**Comment by Sven65** [comment] 2020-12-11 09:46
No updates on this, closing it. If you want to suggest something similar again, please do so at the "Discussion" tab.

**Closed by Sven65** 2020-12-11 09:46 UTC
