### ISSUE TITLE
Pet does not die

### ISSUE THREAD

**Issue by Megapokewar** [DiscordDungeons/Bugs#759] opened 2018-11-12 11:29 UTC
**Describe the bug**
The pet takes damage, more that what it currently has but doesn't die.

**To Reproduce**
1. Let a pet die, i.e. Reach 0 health [I had Rectex at the moment]
2. In a middle of an adventure, Especially one that can kill the pet in one shot. (But it happened when I encountered a monster that dealt 10 damage consistently [Deldu] and I reached 10 health) heal the pet with #!pheal {I had my pet heal set to Lemons}
3. The pet deals Damage but doesn't faint.

**Expected behavior**
You should see a pet that Deals its full damage without fainting (Reach 0 health)

**Screenshots**
![screenshot 5](https://user-images.githubusercontent.com/44969230/48344790-0dcdef80-e6b1-11e8-8a1a-06841c051422.png)
![screenshot 7](https://user-images.githubusercontent.com/44969230/48344799-13c3d080-e6b1-11e8-8912-10639fc5429a.png)
![screenshot 8](https://user-images.githubusercontent.com/44969230/48344804-17575780-e6b1-11e8-8459-466fad6e513c.png)
![screenshot 9](https://user-images.githubusercontent.com/44969230/48344808-1aeade80-e6b1-11e8-8a65-9b683a4661c5.png)

**Version**
What is the current version at the time of creating this issue? (Idk the current one as of 11/12/2018)

**Additional context**
It happened Twice.

**Comment by RainTheVappy** [comment] 2018-11-12 13:10
Pet won't die, instead, it'll deal no damage.
Not a bug.

**Comment by Megapokewar** [comment] 2018-11-12 13:41
uhhh No It deals damage see the screen
![screenshot 10](https://user-images.githubusercontent.com/44969230/48350661-e1bb6a00-e6c2-11e8-8ce9-cd67c1f98e27.png)
shot
The previous Adventure, the Enemy had "The enemy Largyfo has 390/900 HP left."
I dealt "Dealt 39 HP Damage", by rolling 2 "Rolled a 2" 
The pet at 1 hp that doesn't die deals 'Flibknort dealt 47 HP damage.'
390-39-47=304
![screenshot 12](https://user-images.githubusercontent.com/44969230/48350871-6dcd9180-e6c3-11e8-9048-1bb8118f310e.png)
And exactly it reports "The enemy Largyfo has 304/900 HP left."
Therefor the pet doesn't take damage but deals damage.
Either way, even if the pet doesn't deal damage it still a bug as the pet should be KOed when it gets dealt by damage that is higher than its total health.

**Comment by Willard21** [comment] 2018-11-12 15:01
More specifically they don't die twice in 1 battle, which is of course a bug. I was able to reproduce it, so should be fixed soon:tm:

**Closed** 2018-11-13 10:47 UTC
Labels: Bug, Review
