### ISSUE TITLE
Travel bug

### ISSUE THREAD

**Issue by Killer-S-serious-no-underscode-in-name** [DiscordDungeons/Bugs#1005] opened 2021-06-06 23:42 UTC
So I travel from grimstone to maple grove,the bot ‘geniously’ pick the short way that need membership

1. Go to blimstone(that kingdom)
2. Travel to primeval or illeria
3. It will show you need membership

**Expected behavior**
It should use the longer but don’t need membership way

**Version**
Version 4.15.6
![22F5B060-3EBC-4077-BFD0-68575D059EA4](https://user-images.githubusercontent.com/84571012/120943822-e30e7f80-c763-11eb-924e-22de85c28e7a.jpeg)

**Comment by FelixArgyle** [comment] 2021-06-07 05:04
Not a bug, just was never intended to be added for routing.
the routing doesn't check if a user has an active membership, it just simply checks the shortest route.
// if you want better auto-routing then you can suggest for it to be added over at [Ideas/Suggestion](https://github.com/DiscordDungeons/Bugs/discussions/categories/ideas)

**Comment by Sven65** [comment] 2021-06-07 07:45
Is there a possible non-membership route here? If that is the case, it should be prefered when the user doesn't have a membership.

@Willard21 Wanna take a look?

**Comment by FelixArgyle** [comment] 2021-06-07 14:36
Yup there is a non-membership route
Willard just didn't make the routing thing apply with checking of membership or anything, he just simply made it pick out the shortest route.
_that why i said they can suggest better auto-routing in the ideas part, since it more feature upgrade than a bug_

**Comment by Willard21** [comment] 2021-06-07 18:17
It's kinda complicated honestly. I can't just say "path around locations that require membership if you don't have membership." That would causes membership locations to appear unreachable.

Maybe we could add a "shortcut" property to locations that can be pathed around. I'm pretty sure there's only 1.

**Comment by Sven65** [comment] 2021-06-07 18:57
I see, wouldn't we be able to filter locations based on whether or not they're members only before calculating the path?

**Comment by Willard21** [comment] 2021-06-07 23:05
Depends on whether every location that's only reachable by members is already marked members-only. Would you happen to know if that's the case? For example if Buckleport was members-only then all of Lemontree would only be accessible to members, even if the rest of the locations were technically public.

**Comment by Sven65** [comment] 2021-06-08 06:10
All locations that are members-only are marked as such. What I'm proposing is to filter those out of the array of locations used to calculate the path before actually doing the calculation, and returning if there's no valid path found.

**Comment by Willard21** [comment] 2021-06-08 11:34
In that case, yeah it could work. If attempting to path to a members-only location while not a member, use current behavior. If attempting to path to a non-members location while not a member, treat members-only locations as impassible.

**Comment by Sven65** [comment] 2021-10-13 11:09
Is this still an issue?

**Comment by Sven65** [comment] 2022-05-09 09:59
This should be fixed in the beta. If not, re-open the bug.

**Closed by Sven65** 2022-05-09 09:59 UTC
Labels: Needs more info, Other
