### ISSUE TITLE
Armors with Boosts

### ISSUE THREAD

**Issue by KCCAsiPri** [DiscordDungeons/Bugs#726] opened 2018-09-07 19:34 UTC
Issue: 
I have three XP boosting pieces of armor amd one necklace, but the XP boost doesn't work. In total it should add up to 11% increase (I am level 225, but I should be getting exp as someone who is level 247). Yet I still get the same amount of xp (from the Aldebaran bot)

Reproduction:
No current way but to check out my grinding

**Comment by RainTheVappy** [comment] 2018-09-08 00:37
This is NOT Aldebaran support server or report bugs page

**Comment by KCCAsiPri** [comment] 2018-09-08 11:27
The difference in xp is about 300.

**Comment by ryudragon98** [comment] 2018-09-08 14:27
this github is not for aldebaran if you have questions/issues that involve aldebaran then take it to aldebarans support server.

**Comment by KCCAsiPri** [comment] 2018-09-08 17:06
Oh my gosh I'm literally saying that Aldebaran is only proof... 
THE MAIN POINT IS 
THAT I don't get the PROJECTED AMOUNT OF XP (of a level 247) BECAUSE THAT'S THE ESTIMATE OF WHAT I'm SUPPOSED TO GET

**Comment by KCCAsiPri** [comment] 2018-09-08 17:07
It has almost nothing to do with Aldebaran, it is entirely of the xp boost stats on the armors. In other words, they're broken.

**Comment by PlayTheFallen** [comment] 2018-09-08 17:26
Duplicate of #632 
and... Aldebaran has nothing to do with us, it has absolutely no physical interaction with any of the game.

**Closed by PlayTheFallen** 2018-09-08 17:26 UTC
