### ISSUE TITLE
Dungeon heal bug

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#869] opened 2019-11-20 02:58 UTC
**Describe the bug**
If you heal before clicking the reaction when you use `#!dungeon start` the potions you used to heal does not actually heal you.

[Updated] seems like it's a visual bug, during the running phases, I landed on a chest but never opened it and it put me in a fight (not sure what would cause that), I killed the mob and noticed the health was as it should have been

**To Reproduce**
1. Type `#!dungeon start` at a redhorn dungeon
2. BEFORE clicking the reaction use `#!heal auto`
3. After (2.) click the reaction

**Expected behavior**
Expect that the heal a user has done is to take effect into the dungeon.
**Screenshots**
![9zWb2fj](https://user-images.githubusercontent.com/12903523/69205343-09be9280-0b8d-11ea-8418-650d6c2ab12c.png)
![5QanXdV](https://user-images.githubusercontent.com/12903523/69205344-0a572900-0b8d-11ea-940a-513b410eef77.png)

**Version**
4.12.4 
**Additional context**
What might have caused it is that once you use `#!dungeon start` that starts the dungeon even if you haven't accepted with the reaction to go forth.

**Comment by Willard21** [comment] 2019-11-20 03:03
I swear I've fixed this like twice lol. Must have been on branches I never merged. It's caused by the bot loading your stats as soon as you enter the command (has to check your level and location and stuff), so your stats are saved from before you click the OK button. We basically just need to load your stats a second time after you click OK.

**Comment by Willard21** [comment] 2019-11-20 13:47
Oh jk, I really did fix the stats thing. Health just gets synced separately from stats to make dungeons faster. That happens before you click OK.

**Comment by Willard21** [comment] 2019-11-20 13:54
Mkay fixed. In the meantime, if you cause this bug and remember before you encounter an enemy, you can do #!dungeon status and it'll correct your health in the dungeon.

**Closed** 2019-11-22 09:59 UTC
Labels: Bug
