### ISSUE TITLE
Guild role bug

### ISSUE THREAD

**Issue by NekoMaidSakuya** [DiscordDungeons/Bugs#449] opened 2017-11-20 11:53 UTC
Few hours ago rj made me a owner of rebirth, so i tried to make rj elder but it said that i dont have permission so i checked members and i noticed that i am elder and owner

heres screenshot: https://cdn.discordapp.com/attachments/306484491566841857/382136135461240832/unknown.png

**Comment by Sven65** [comment] 2017-11-21 07:41
Duplicate of #445

**Closed by Sven65** 2017-11-21 07:41 UTC
