### ISSUE TITLE
Error with fishing

### ISSUE THREAD

**Issue by icepheonix5** [DiscordDungeons/Bugs#206] opened 2017-05-30 17:32 UTC
Everytime I try to fish I just get this error https://gyazo.com/c2e1545c81230ac66041dc0a1eba12f9

**Comment by Maxxxel** [comment] 2017-05-30 17:46
duplicate of #183

**Comment by Sven65** [comment] 2017-05-31 05:12
Already reported in #183 as @Maxxxel said.

**Closed by Sven65** 2017-05-31 05:12 UTC
Labels: Bot, bug, duplicate
