### ISSUE TITLE
🐛 Bug Report:

### ISSUE THREAD

**Issue by WhitmanFudo** [DiscordDungeons/Bugs#1382] opened 2024-07-31 15:04 UTC
### 👟 Reproduction steps

I talk to Tobin in Lake of 100 Winters for a mission inicialization

### 👍 Expected behavior

The quest work property

### 👎 Actual Behavior

![image](https://github.com/user-attachments/assets/b028cd89-6953-4b56-ac2f-6a9f3d3b69b2)

### 💥 Error message

```
TypeError: Cannot set properties of undefined (setting 'emoji')
    at NamazuQuest.continueCheckMessage (/bin/src/Data/Quest/Quest.ts:462:24)
    at NamazuQuest.continueCheckDialog (/bin/src/Data/Quest/Quest.ts:440:15)
    at NamazuQuest.handleStage (/bin/src/Data/Quest/Quests/NamazuQuest.ts:103:36)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at TalkCommand.handleQuest (/bin/src/SlashCommands/Commands/Location/Talk.ts:742:4)
    at TalkCommand.run (/bin/src/SlashCommands/Commands/Location/Talk.ts:973:18)
    at originalCommandRunner (/bin/src/Bot.ts:121:18)
```

### 🎲 DRPG version

v4.18.49

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment] 2024-08-20 13:07
Duplicate of #1380

**Closed as completed by Sven65** 2024-08-20 13:07 UTC
