### ISSUE TITLE
🐛 Bug Report: chop occasionally returns a false negative

### ISSUE THREAD

**Issue by Weebs666** [DiscordDungeons/Bugs#1255] opened 2022-08-22 04:45 UTC
### 👟 Reproduction steps

When I run /chop

### 👍 Expected behavior

It should return with the logs I have chopped, assuming I am at a location with permission for a chop side.

### 👎 Actual Behavior

 It sometimes replies with "The application did not respond" however the number of logs I have in my inventory actually increases by the amount I would expect.

### 🎲 DRPG version

4.18.5

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

I have not seen this on the other sides but I would expect them to have a similar issue

**Comment by mount2010** [comment] 2022-08-22 06:05
This doesn't only happen with chop, it happens with everything at random. We're trying to figure out the cause.

**Comment by mount2010** [comment] 2022-08-22 09:26
Duplicate of #1244

**Closed by mount2010** 2022-08-22 09:26 UTC
Labels: Duplicate
