### ISSUE TITLE
🐛 Bug Report: Plant check bug occurs 

### ISSUE THREAD

**Issue by Killer-S-serious-no-underscode-in-name** [DiscordDungeons/Bugs#1152] opened 2021-12-11 02:51 UTC
### 👟 Reproduction steps

![23A35C1C-A433-4872-ACA7-A2D80B86C386](https://user-images.githubusercontent.com/84571012/145661228-21e92501-e245-4bb4-9fd7-ec9c1700f772.jpeg)
When I use command #!plant check,a but occurred 

### 👍 Expected behavior

It should show "Killer__s/ checked the <Seed Name> they planted about <Time you left it> ago.
There was <Number of crop> leftover."

### 👎 Actual Behavior

Bug occurred and I'm not sure I got anything or not

### 🎲 DRPG version

4.17.7

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment] 2021-12-17 09:41
Sort of duplicate of #1136

**Closed by Sven65** 2021-12-17 09:41 UTC
