### ISSUE TITLE
Discord RPG bot stopped responding in one channel to everyone

### ISSUE THREAD

**Issue by Dragoneyr** [DiscordDungeons/Bugs#838] opened 2019-07-13 09:13 UTC
**Describe the bug**
The bot has stopped responding to all commands. When doing #!adv or #!ping, it does not respond to the commands, used by anyone.
The chat channel is: 452498968056954880

**To Reproduce**
It's unclear how to reproduce this behavior. The bot works fine in other chat channels of that same server. All I did was adv-ing and it just stopped responding entirely

**Expected behavior**
When doing adventures or really just any command, the bot should have responded to those.

**Screenshots**
![Screenshot_20190713-110430_Discord](https://user-images.githubusercontent.com/52624311/61169531-2273c780-a55f-11e9-9e3e-17b7308e8d76.jpg)
![Screenshot_20190713-110406_Discord](https://user-images.githubusercontent.com/52624311/61169532-2273c780-a55f-11e9-896f-f6cf29dcc304.jpg)

**Version**
Latest: 2.12.1

**Comment by sk-555** [comment] 2019-07-13 12:23
This happened to me and a few others as well (only stopped working in a single channel). Another interesting thing to note is that the bot's commands still execute (ex. if you were using `#!adv`, the adventure would go through, you would get gold/xp for killing a mob, etc.) despite not being displayed.

Unfortunately the only solution we could find was either recreating the channel (deleting and recreating) or moving to a new channel. Would like to see the cause of this problem

**Comment by Willard21** [comment] 2019-07-14 22:55
I can *sorta* reproduce it by deleting a channel from the channel cache in a bot. The difference is that the bug causes the bot to still read messages without being able to respond to them, whereas removing the channel from the cache also makes it stop reading messages. So it's probably not that.

**Comment by Sven65** [comment] 2019-10-22 07:25
Closed due to being stale.

**Closed by Sven65** 2019-10-22 07:25 UTC
