### ISSUE TITLE
Guild owner counted as an elder and owner at the same time

### ISSUE THREAD

**Issue by Willard21** [DiscordDungeons/Bugs#883] opened 2019-12-01 17:25 UTC
**Describe the bug**
When an elder has guild ownership transferred to them, they continue to be listed as an elder. That also causes the member count to be 1 less than it really is in #!guild since the guild owner is subtracted twice.

**To Reproduce**
1. #!grole @user1 elder
2. #!grole @user1 owner
3. #!gmembers
4. See user1 listed as both the owner and an elder

**Comment by PlayTheFallen** [comment] 2019-12-01 17:48
Isn’t this a dupe of #79?
@Sven65 closed it back around 2 years ago, saying no fix was needed.

Sent from Mail for Windows 10

From: Will Ashworth
Sent: 01 December 2019 17:25
To: DiscordDungeons/Bugs
Cc: Subscribed
Subject: [DiscordDungeons/Bugs] Guild owner counted as an elder and owner atthe same time (#883)

Describe the bug
When an elder has guild ownership transferred to them, they continue to be listed as an elder. That also causes the member count to be 1 less than it really is in #!guild since the guild owner is subtracted twice.
To Reproduce
1. #!grole @user1 elder
2. #!grole @user1 owner
3. #!gmembers
4. See user1 listed as both the owner and an elder

**Comment by Willard21** [comment] 2019-12-01 17:52
O. Looks like dupe yeah. But Mackan seemed to think it couldn't be reproduced, which is false.

**Comment by Sven65** [comment] 2020-12-11 08:26
Fixed in the same pr as #871

**Closed by Sven65** 2020-12-11 08:26 UTC
Labels: Bug, Guild
