### ISSUE TITLE
🐛 Bug Report:

### ISSUE THREAD

**Issue by gehhanna** [DiscordDungeons/Bugs#1383] opened 2024-08-01 00:04 UTC
### 👟 Reproduction steps

Using command /adv 

### 👍 Expected behavior

![image](https://github.com/user-attachments/assets/9f419e86-aa2a-4dec-bad8-4259e7b5e767)

### 👎 Actual Behavior

![image](https://github.com/user-attachments/assets/0aa51b94-6718-4155-aed7-19f4682fcc73)

### 💥 Error message

```
Error: getaddrinfo EAI_AGAIN wireguard-db-proxy-service.wireguard.svc.cluster.local
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
```

### 🎲 DRPG version

v4.18.49

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment] 2024-08-20 13:06
Duplicate of #1381. Please actually check next time.

**Closed as completed by Sven65** 2024-08-20 13:06 UTC
