### ISSUE TITLE
#!gblist issue

### ISSUE THREAD

**Issue by shroomyun** [DiscordDungeons/Bugs#674] opened 2018-05-14 08:12 UTC
#!gmglist is fine, something wrong with #!gblist just now (this is on main server)
![_20180514_162027](https://user-images.githubusercontent.com/33994869/39985564-936623a6-5791-11e8-9ce9-be56f366f8ae.JPG)

**Comment by Sven65** [comment] 2018-05-14 08:13
Caused by me doing some testing, fixed now.

**Closed by Sven65** 2018-05-14 08:13 UTC
