### ISSUE TITLE
#!travel bug

### ISSUE THREAD

**Issue by Pondering73** [DiscordDungeons/Bugs#885] opened 2019-12-01 19:43 UTC
#!travel brings up an error. Refer to screenshot.

![Screenshot_20191201-131724_Discord](https://user-images.githubusercontent.com/58401297/69919252-934d4a80-1440-11ea-814e-5540171964bd.jpg)

**Comment by Willard21** [comment] 2019-12-01 20:58
Duplicate of #877

**Closed** 2019-12-01 20:57 UTC

**Comment by Pondering73** [comment] 2019-12-02 00:02
Is it the same? I'm not in a party

**Comment by Willard21** [comment] 2019-12-02 00:04
Yeah. You can see it's the same error message on both. Do `#!party` to fix it if you're not actually in a party.
