### ISSUE TITLE
Iron Ore mining level issue

### ISSUE THREAD

**Issue by Paputcsallatka** [DiscordDungeons/Bugs#922] opened 2020-03-27 18:40 UTC
**Describe the bug**
Yesterday iron ore mining level changed from 1 to 8.

**To Reproduce**
type #!item iron ore

**Expected behavior**
Changing the iron ore mining level back to 1

**Screenshots**
<img width="390" alt="2020-03-27 o 19 35 21" src="https://user-images.githubusercontent.com/62767752/77789152-ce643100-7062-11ea-8fee-9be8364baa1b.png">
<img width="320" alt="2020-03-27 o 19 35 38" src="https://user-images.githubusercontent.com/62767752/77789165-d15f2180-7062-11ea-908c-884f4f003a35.png">

**Comment by FelixArgyle** [comment] 2020-03-27 23:27
> **Describe the bug**
> Yesterday iron ore mining level changed from 1 to 8.
> 
> **To Reproduce**
> type #!item iron ore
> 
> **Expected behavior**
> Changing the iron ore mining level back to 1
> 
> **Screenshots**
> <img alt="2020-03-27 o 19 35 21" width="390" src="https://user-images.githubusercontent.com/62767752/77789152-ce643100-7062-11ea-8fee-9be8364baa1b.png">
> <img alt="2020-03-27 o 19 35 38" width="320" src="https://user-images.githubusercontent.com/62767752/77789165-d15f2180-7062-11ea-908c-884f4f003a35.png">

Not a bug, ores mine levels changed to match the order of how you'd achieve pickaxes
i.e copper > zinc > iron > leptocite
(your best to close the issue btw)
- Do see on how it can conflict with crafting a compass, nonetheless your not in any hurry to travel around, always optional to use the market to buy materials or a compass itself

**Comment by Willard21** [comment] 2020-03-28 05:11
Lowered to 4.

**Closed by Willard21** 2020-03-28 05:11 UTC
