### ISSUE TITLE
Selling Bug

### ISSUE THREAD

**Issue by splayy** [DiscordDungeons/Bugs#706] opened 2018-07-21 15:15 UTC
**Describe the bug**
When I sold my rock salt, I didn't receive any gold

<img width="459" alt="screen shot 2018-07-21 at 10 43 45 am" src="https://user-images.githubusercontent.com/41516427/43037103-523a624a-8cd7-11e8-9ca4-22316e98668f.png">
<img width="605" alt="screen shot 2018-07-21 at 10 43 55 am" src="https://user-images.githubusercontent.com/41516427/43037104-533e8e46-8cd7-11e8-85b8-299757ba1fb5.png">

**Comment by RainTheVappy** [comment] 2018-07-22 02:33
You should not use alias to sell "all" items, it'll cause that

**Comment by Sven65** [comment] 2018-07-22 07:20
Duplicate of #668

**Closed by Sven65** 2018-07-22 07:20 UTC
