### ISSUE TITLE
🐛 Bug Report: #!talk failure with Urist

### ISSUE THREAD

**Issue by n00lesscluebie** [DiscordDungeons/Bugs#1179] opened 2022-02-22 12:13 UTC
### 👟 Reproduction steps

When I talk to Urist in Redhorn and get the 3 reactions to respond to him, any of the three produce a small red “! This Interaction Failed” and the dialogue can not continue.  If I try to talk to him again I get a “You are already talking to someone” response from the bot.   I can switch locations and return and can talk to him again but get the “! This interaction failed” error

### 👍 Expected behavior

Clicking on the 1, 2 or 3 would cause Urist to respond with upgrades/socketing

### 👎 Actual Behavior

![671C557A-D739-4484-B265-E9AA3B34ACB0](https://user-images.githubusercontent.com/100206059/155129953-4758fd7c-7b6f-4c75-85d8-913b8a55f767.jpeg)
![9AA83545-CE71-4B8C-8B13-5DC4C1891541](https://user-images.githubusercontent.com/100206059/155129960-ad08012e-06bb-4c50-8a19-124ae375862d.jpeg)

### 🎲 DRPG version

4.17.13

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

I just turned level 50

**Comment by n00lesscluebie** [comment] 2022-02-22 12:22
Note:   This only seems to be a problem while using the iPhone Discord app.   The issue is not reproducible on my Mac Discord app!

**Comment by Sven65** [comment] 2022-03-19 14:16
Hi! Apologies for the late reply. Are you on the latest version of the discord app, and if so, is this still an issue?

**Comment by Sven65** [comment] 2022-04-29 06:33
Can't reproduce, fixed in beta.

**Closed by Sven65** 2022-04-29 06:33 UTC
