### ISSUE TITLE
Unable to #!adventure

### ISSUE THREAD

**Issue by Carsnip1** [DiscordDungeons/Bugs#761] opened 2018-11-14 06:11 UTC
**Describe the bug**
Whenever I use #!adv or #!adventure, absolutely nothing happens. If I try to do it again, it will give me the ~12s cooldown but still nothing will happen.
However; I am able to use every other command that I have thought of. #!mine, #!chop #!buy.
Using #!stats I am able to see that my health is not changing, clarifying that #!adv is not doing anything.

**To Reproduce**
Type #!adv
Nothing happens

**Expected behavior**
A print of the adventure screen, showing damage dealt and damage received.

**Version** (from #!debug) 
DRPG 4.3.24
Cobra 3.0.1
d.js Version 11.4.2

**Additional context**
This happened around yesterday morning (nov 12th) without much prompt to it. I just logged in and was unable to adventure.

**Comment by Willard21** [comment] 2018-11-14 06:16
Duplicate of #760 (also already fixed)

**Closed** 2018-11-14 10:48 UTC
Labels: Review

**Comment by Carsnip1** [comment] 2018-11-14 17:51
Working perfectly this morning. Thank you!
