### ISSUE TITLE
Error thrown using #!stats command

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#784] opened 2019-01-04 23:00 UTC
**Describe the bug**
Well, I'd no clue what would cause this `Cannot read property 'highestRole' of undefined` seems like it's only happening to the user shown in the pic tho.  The user started 2 years ago so could be related to that on why it's throwing this error.
**To Reproduce**
1. The user in the pic below typed `#!stats`
2. Returns the Error below
```js
TypeError: Cannot read property 'highestRole' of undefined
    at Promise (/home/mackan/RPGBot/src/Util/Common.js:27:252)
    at Promise (<anonymous>)
    at Object.setNick (/home/mackan/RPGBot/src/Util/Common.js:25:10)
    at Stats.Execute (/home/mackan/RPGBot/src/Commands/Commands/User/Stats.js:235:11)
    at <anonymous>
```

**Expected behavior**
Shouldn't return the error

**Screenshots**

![581418](https://user-images.githubusercontent.com/12903523/50715218-9c625a00-10bf-11e9-821d-c12a66bd3c85.png)

**Version**
4.6.0 

**Additional context**
The users started date + userID
150012525331611649 started 27 Jun 2016 01:01:08, 2 years ago.

**Comment by PlayTheFallen** [comment] 2019-01-04 23:30
It's trying to set your nickname.

**Comment by Willard21** [comment] 2019-01-05 00:41
Yeah it's the nickname. The problem is actually just that the user hasn't been cached in the server yet (or something like that), so it might work for them in another server. Another user had the same issue, so I pushed a fix for it a couple days ago, and should be fixed in the next update. I couldn't reproduce it on my test bot, so I'll leave this open until we can confirm it's fixed.

`#!uset nick 0` probably throws the same error, but if not, they can try that to see if it fixes it.

**Comment by Willard21** [comment] 2019-01-06 14:49
Appears to be fixed now.

**Closed by Willard21** 2019-01-06 14:49 UTC
