### ISSUE TITLE
uset nick # - issues with modes 1 and 3

### ISSUE THREAD

**Issue by loopyd** [DiscordDungeons/Bugs#690] opened 2018-06-19 08:09 UTC
**Please describe your issue below.**  

> __Note__:  Have verified nick and user account name on Discord __do not__ contain Unicode, and is shorter than 16 characters.

``#!uset nick 1`` and ``#!uset nick 3`` do not function at all.  The only mode which seems to respond correctly and update your nickname is ``#!uset nick 2`` .

**If an error is provided, please copy the block into the space below.**

```js

< nothing happens, unless you specify nick mode 2 >

```

**Comment by Templexx** [comment] 2018-06-19 17:11
Uset 1: [Clan Icon] ... [Lvl.41]
Uset 2: Clan Icon ... Lv41
Uset 3: Clan Icon ... [Lvl.41]

**Comment by PlayTheFallen** [comment] 2018-06-22 10:13
Duplicate of #637 *your own to be exact*

| Format | Result | Length |
| --- | --- | --- |
| 1 | `[Donator] [🌌] LupineDream [Lvl. 438]` | 37 |
| 2 | `🌟 \| 🌌 \| LupineDream Lv438` | 27 |
| 3 | `🌟 \| 🌌  \| LupineDream [Lvl. 438]` | 33 |

**Closed by PlayTheFallen** 2018-06-22 10:13 UTC

**Comment by loopyd** [comment] 2018-06-25 00:33
So by this logic, my actual discord username has to be shorter than 5 characters  because of the extra things the bot is tacking on going over the limit.

OK.  Sorry.  _No need to italicize._

*shrug*
