### ISSUE TITLE
Attribute points issue

### ISSUE THREAD

**Issue by iSaluki** [DiscordDungeons/Bugs#806] opened 2019-02-21 09:17 UTC
I cannot assign any new attribute points. I levelled up to level 3 and then got 5 points. I assigned 2 to strength and that worked fine. Then I assigned 2 to luck but the not ignored the command. The same happened when I tried to assign the last one to charisma.

**Comment by Saederup92** [comment] 2019-02-21 09:18
Try running `#!attributes`. Luck and charisma are no longer attributes that can be assigned to :)

**Comment by iSaluki** [comment] 2019-02-21 09:30
Thanks. That's working. I was following the Wiki on that one (the starter guide page is a bit outdated).

**Comment by Saederup92** [comment] 2019-02-21 09:36
The wiki still needs some reworking

**Comment by Willard21** [comment] 2019-02-21 14:24
Yup, wiki is super outdated, but it's not a bug so I'll close this.

**Closed by Willard21** 2019-02-21 14:24 UTC
