### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by aaronlilly** [DiscordDungeons/Bugs#1124] opened 2021-11-14 00:26 UTC
Whoops. An error occured.
To report it, go to the link in ,,bug, or visit ,,serverinvite for support.
QueryFailedError: null value in column "created" violates not-null constraint
    at QueryFailedError.TypeORMError [as constructor] (/bin/rpgbot/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/bin/rpgbot/src/error/QueryFailedError.ts:9:9)
    at PostgresQueryRunner.<anonymous> (/bin/rpgbot/src/driver/postgres/PostgresQueryRunner.ts:258:19)
    at step (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
    at rejected (/bin/rpgbot/node_modules/typeorm/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by aaronlilly** [comment] 2021-11-14 00:26
can't do anything

**Comment by mount2010** [comment] 2021-11-14 01:44
Duplicate of #1119

**Closed by mount2010** 2021-11-14 01:44 UTC
