### ISSUE TITLE
🐛 Bug Report: Upgrade weapon at Redhorn took cash said it worked but did not

### ISSUE THREAD

**Issue by Weebs666** [DiscordDungeons/Bugs#1153] opened 2021-12-13 23:10 UTC
### 👟 Reproduction steps

I talked to Urist at Redhorn to get my Accelerator's Premium Lance 2SXR+32 upgraded by 1 to be Accelerator's Premium Lance 2SXR+33.

### 👍 Expected behavior

Say successful and put the Accelerator's Premium Lance 2SXR+33 in my inventory and reduce my gold by 150,491,923

![expected](https://user-images.githubusercontent.com/94192849/145903382-76f6b508-d38c-494d-864b-9ac3f25bf091.jpg)

### 👎 Actual Behavior

Said it was successful but did not upgrade the weapon and put the Accelerator's Premium Lance 2SXR+32 in my inventory and reduced my gold by 150,491,923
![Actual](https://user-images.githubusercontent.com/94192849/145903527-9888f4a6-2b27-4877-9e69-a6848cc8eb36.jpg)

### 🎲 DRPG version

4.17.7

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

This is the first time I have tried to update my weapon since the new version. 
I don't know if this is a new bug or an existing bug which has manifest itself.

**Comment by Weebs666** [comment] 2021-12-13 23:16
Might be related to 1067 and 1104

**Comment by Sven65** [comment] 2021-12-15 08:13
Did you check the item on different shards?

**Comment by Weebs666** [comment] 2021-12-15 08:26
It was not working on the main discord bot, the-north-pole, and it was not working on shard-10 which is where my own Discord Server run's the bot.

I will be moving to a new weapon soon, 3 hours running,  and will do a whole lot of gold grinding, ~ 8 hours,  to get it to the level I need to one-shot again. As such I will check this on as many shards as I can. 

Question does the main discord bot and all of it's channels run in the same shard or should I confirm that each channel is on a different shard and if so I can check it on each unique shard/channel I can.

**Comment by FelixArgyle** [comment] 2021-12-15 08:32
shard is server based (channels not run on different shards)
_i might go test real quick to do smol upgrades on some random weapon just to see if it is refreshing on different shards + the shard you run the command on_

**Comment by FelixArgyle** [comment] 2021-12-15 08:36
working fine on 4 different shards so far (so gonna assume it the same for all.. there no way for me to test all kek)
guess it just gonna be a common occurrence where it randomly is going to happen where items/meta items aren't getting refreshed  🤔

**Comment by Weebs666** [comment] 2022-03-23 03:37
Updated information. 
Happened again yesterday
Upgraded weapon from GRSS 2SRR+33 to GRSS 2SRR+34 after the server restart this morning. 

Not seeing the weapon on shard-10 or shard-56 ( rpg-island ) in my inventory. 

The only other server I occasionally run on is on shard-28 I am seeing it in there.

**Comment by FelixArgyle** [comment] 2022-04-12 01:18
> I think this is related. I had the same thing occur with a socket. ![image](https://user-images.githubusercontent.com/103469517/162855567-da601049-ac7e-4bfe-80fd-89c0e1ae6700.png) ![image](https://user-images.githubusercontent.com/103469517/162855783-dc9f1aa2-fed3-455c-b69b-88041db0d8b5.png)

it's going to keep happening, it's already highly aware and the problem is known, issue sadly will get fixed whenever the slash command update comes since that's what the devs are working towards since discord has a deadline for message intent changes to be in effect

**Comment by Sven65** [comment] 2022-05-09 10:29
This has been fixed in the beta version of the bot, and will be released with that. I'll be leaving the issue up until then.

**Comment by Sven65** [comment] 2022-10-22 08:52
As it's been released, I'll close the issue.

**Closed by Sven65** 2022-10-22 08:52 UTC
Labels: Bug, Fixed, Needs more info
