### ISSUE TITLE
#!uset nick 1 seems to be broken for some users (Including myself)

### ISSUE THREAD

**Issue by KawaiiArtistAlex** [DiscordDungeons/Bugs#252] opened 2017-07-04 12:16 UTC
Hi, so I've just tried to use the command `#!uset nick 1` and it seems not to display anything after the use, `#!uset nick 2` works however.
This is in the main Discord RPG server it.
It also seems to work for few amount of players.
Here are some screenshots to show the command use.
![614ae6](https://user-images.githubusercontent.com/12903523/27829720-e83a1546-60ba-11e7-876f-0690aaa09e17.png)
![f9e68b](https://user-images.githubusercontent.com/12903523/27829721-e83d3c9e-60ba-11e7-907e-be02fc23ccbf.png)

**Comment by prototypep3** [comment] 2017-07-04 12:53
This would probably be because the nick ends up too long and goes over the character limit.

**Comment by KawaiiArtistAlex** [comment] 2017-07-04 13:00
I shortened my nick to just "Felix" what is short amount of characters and it still appeared to not list the nick to work, it worked before with my nick name as the same just "Felix Argyle" what could be found in the main DisocrdRPG server, although I'm thinking it could be as I have donated so it's possible that the [ Donator ] is out putting it to be over the character limit, so I think then there should be an option to set the donator tag off possibly.

**Comment by prototypep3** [comment] 2017-07-04 13:03
Do you mean you shortened your nick or you shortened your username? Because if you only shortened your nick it won't make a difference. The bot uses your name not your nick for the levels. And yes you have to factor in the "donator" tag into the name too.

**Comment by KawaiiArtistAlex** [comment] 2017-07-04 13:13
I shortened my Discord username.

**Comment by prototypep3** [comment] 2017-07-04 13:27
Are you a donator?

**Comment by KawaiiArtistAlex** [comment] 2017-07-04 13:56
I am.

**Comment by prototypep3** [comment] 2017-07-04 14:46
Basically if you're a donator and you have a guild tag your name can't be more than 3-5 characters long.

**Comment by SamuiNe** [comment] 2017-07-16 23:41
Since this is not a bug and the issue has been solved, I'm going to close the issue.

**Closed** 2017-07-16 23:41 UTC
Labels: Invalid
