### ISSUE TITLE
Stats Scroll displays chestplate as boots.

### ISSUE THREAD

**Issue by TheConceptionist** [DiscordDungeons/Bugs#52] opened 2016-10-24 21:11 UTC
https://cdn.discordapp.com/attachments/239110862856650753/240219829951397888/file.jpg

**Comment by SnazzyPine25** [comment] 2016-10-24 22:01
Not a bug in my code. Blame Mackan.

**Comment by Sven65** [comment] 2016-10-25 06:54
Should be fixed.

**Closed by Sven65** 2016-10-25 06:54 UTC
Labels: bug, Other
