### ISSUE TITLE
Unable to `#!item` garland garden shears when it is enchanted.

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#892] opened 2019-12-14 03:10 UTC
**Describe the bug**
Unable to `#!item` garland garden shears when it is enchanted.

**To Reproduce**
1. Enchant that Garland Garden Shears with gems or so
2. Try using Unable to `#!item garland garden shears 2SRR` or whatever enchant you put on
This will show that the item does not exist.

**Expected behavior**
Expect it to show up when I try and use item on the item

**Screenshots**
Screenshot of me trying to use item on it
http://felix.is-a-good-waifu.com/Y4rjUNF.png

**Version**
4.13.2 

**Additional context**
pls fix

**Comment by Willard21** [comment] 2019-12-14 03:18
Duplicate of #890 It was shown in the screenshot in #890 even though he didn't mention it. (I fixed it in my fix for that)

**Closed by Willard21** 2019-12-14 03:18 UTC
