### ISSUE TITLE
Cannot go to the next page of guild members list?

### ISSUE THREAD

**Issue by MaxWong0826** [DiscordDungeons/Bugs#228] opened 2017-06-15 04:52 UTC
As the question says everything.

**Comment by SamuiNe** [comment] 2017-06-15 06:15
Can confirm, the bot just says that `No guild was found`.

**Comment by SamuiNe** [comment] 2017-06-15 06:18
This issue is a duplicate of #164 , closing the issue due to this reason.

**Closed by SamuiNe** 2017-06-15 06:18 UTC
Labels: Bot, Bug
