### ISSUE TITLE
#+Talk bug

### ISSUE THREAD

**Issue by Sirfirelord69** [DiscordDungeons/Bugs#1036] opened 2021-09-30 04:19 UTC
**Describe the bug**
Talk command fails on certain NPCs (so far i have only checked Silverkeep)
- Axhor
**To Reproduce**
1. Go to 'Silverkeep'
2. Do `#+talk axhor`
3. See error message
```TypeError: Cannot read properties of null (reading 'stage')
    at Talk._handleQuest (/bin/src/Commands/Commands/Locations/Talk.ts:628:45)
    at Talk.prepareDialog (/bin/src/Commands/Commands/Locations/Talk.ts:822:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Talk.execute (/bin/src/Commands/Commands/Locations/Talk.ts:886:18) ```

**Expected behavior**
Some dialogue, i presume

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Version**
16.4.13-beta

Use `#!info` to find the version.

**Additional context**
Add any other context about the problem here.

**Comment by mount2010** [comment] 2021-09-30 05:45
Duplicate of #1024

**Closed by mount2010** 2021-09-30 05:45 UTC
