### ISSUE TITLE
🐛 Bug Report: Checking Error Message

### ISSUE THREAD

**Issue by Annoymousboy0** [DiscordDungeons/Bugs#1138] opened 2021-11-20 00:59 UTC
### 👟 Reproduction steps

I can't really check my crops, like i used
/plant check cherry seed (prefix modified)
Then it gives me an error message. 
After that my fields is empty.
Can someone fix this annoying bug please...

### 👍 Expected behavior

It should check my crops

### 👎 Actual Behavior

Gave me a error message instead

### 🎲 DRPG version

4.17.2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by FelixArgyle** [comment] 2021-11-20 01:25
@Annoymousboy0 could you maybe put the error the bot gave? it surely helps devs out.
also i'm guessing the issue is already fixed just waiting on a bot update,
if the error is the same to the issue linked below just close the issue @Annoymousboy0 

#https://github.com/DiscordDungeons/Bugs/issues/1132
@Sven65 @mount2010 // btw don't think you should close issues until an update is actually pushed since people won't check closed issues 👍

**Comment by Annoymousboy0** [comment] 2021-11-20 02:09
the error is: 

TypeError: saplingTime.toString(...).timeSince is not a function
    at Plant.checkPlant (/bin/src/Commands/Commands/Sides/Plant.ts:257:135)
    at Plant.execute (/bin/src/Commands/Commands/Sides/Plant.ts:341:5)

**Comment by mount2010** [comment] 2021-11-20 02:32
@FelixArgyle The issues are closed automatically, you can add an awaiting update label to them maybe? 
Yeah people usually don't check closed issues but it's fine to have duplicates so long as people actually report bugs. Takes 10 seconds to mark them as duplicate.

**Comment by Sven65** [comment] 2021-11-30 07:51
Yeah this should be fixed now

**Closed by Sven65** 2021-11-30 07:51 UTC

**Comment by Annoymousboy0** [comment] 2021-11-30 12:38
oh :D
