### ISSUE TITLE
Amethyst Gemstone Effects in #!attributes Display

### ISSUE THREAD

**Issue by sk-555** [DiscordDungeons/Bugs#850] opened 2019-09-01 12:51 UTC
**Describe the bug**
Amethyst gemstone bonus effects do not appear when viewing the Attribute Points display with the `#!attributes` command. I am not sure if they are supposed to, but as this works for other gemstones (Rubies for Strength, Opals for Criticals, Sapphires for XP Boost etc.), I figured that the same result should occur with Amethysts and their 5% defense boosts.

**To Reproduce**
1. Equip at least one Amethyst gemstone on your armor set.
2. Use the `#!attributes` command to receive your user's Attribute Points display.
3. View no noticeable changes to the Defense attribute display.

**Expected behavior**
A +5% boost in the Defense attribute is expected to be displayed, as that is the effect of Amethyst gemstones. An example display, if the user has three Amethysts equipped:

> + Defense: 0 [+15%] (-0 dmg)

As a more cosmetic point, I figured that a display as such

> + Defense: 0 [-15% damage] (-0 dmg)

Would make more sense to keep consistency with the -dmg prompt from Attribute Point effects, but it doesn't work this way with Strength so I suppose it doesn't really matter. 

**Screenshots**
To provide my first example, my Golden Small Dagger gives a passive +3% Gold Boost, which is indicated in the attribute points display:
<img width="233" alt="Screen Shot 2019-09-01 at 8 34 05 PM" src="https://user-images.githubusercontent.com/19984339/64076639-d987f600-ccf9-11e9-9458-42008c53cb0f.png">

Now, I currently have 3 Amethyst gemstones equipped on my armor set, providing a 15% damage decrease. However, it does not appear under the Defense attribute as it does for the Gold Boost attribute above:
<img width="179" alt="Screen Shot 2019-09-01 at 8 34 46 PM" src="https://user-images.githubusercontent.com/19984339/64076647-f8868800-ccf9-11e9-9441-97dc92f82bdd.png">

**Version**
4.12.2

**Comment by Willard21** [comment] 2019-09-01 14:23
Amethysts don't boost the defense *attribute* (which just subtracts a little bit of damage). They increase the damage blocked by the armor it's added to. As damage blocked by armor doesn't appear in the attributes screen, amethysts wouldn't either. I'll close this as it's not a bug, but feel free to make a post on the [ideas page](https://ideas.discorddungeons.me/) if you'd like to suggest different behavior.

Strength also doesn't *technically* boost the "attribute", since the attribute only increases damage by like 20, which is obviously useless. Instead rubies are treated like a strength ring (and stack additively with a strength ring if you wear one), which is kinda hard to describe in a single stat, since it differs from the behavior of the strength attribute.

**Closed by Willard21** 2019-09-01 14:23 UTC

**Comment by sk-555** [comment] 2019-09-01 14:37
Sounds good! Yeah, not an issue then, was just a misinterpretation with how the game handled this. I guess it was a design choice on your guys' end to keep this behavior so it should be fine as it is ^^
