### ISSUE TITLE
Error with #!gset tag

### ISSUE THREAD

**Issue by Maxxxel** [DiscordDungeons/Bugs#185] opened 2017-05-28 13:52 UTC
```
TypeError: Guild.setTag is not a function
    at guildInv.removeItems.then (/home/mackan/RPGBot/src/Commands/Commands/Guild/Gset.js:133:18)
    at tryCatcher (/home/mackan/RPGBot/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/mackan/RPGBot/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/mackan/RPGBot/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
```

when i do #!gset tag LB

**Comment by bubbie** [comment] 2017-05-28 14:37
Duplicate of #181

**Closed** 2017-05-28 15:15 UTC
