### ISSUE TITLE
🐛 Bug Report:

### ISSUE THREAD

**Issue by WhitmanFudo** [DiscordDungeons/Bugs#1384] opened 2024-08-29 15:21 UTC
### 👟 Reproduction steps

I am trying to start the quest with Pope Seth, but I always get this error when I try.

### 👍 Expected behavior

I was supposed to be able to proceed and get the quest from him.

### 👎 Actual Behavior

![image](https://github.com/user-attachments/assets/9b882037-ad8d-4b74-9bf0-f7d853717dda)
![image](https://github.com/user-attachments/assets/16dab3e8-344d-469d-b196-ee8421e1bac2)

### 💥 Error message

```
TypeError: Cannot set properties of undefined (setting 'emoji')
    at COM.continueCheckMessage (/bin/src/Data/Quest/Quest.ts:462:24)
    at COM.continueCheckDialog (/bin/src/Data/Quest/Quest.ts:440:15)
    at COM.handleStage (/bin/src/Data/Quest/Quests/COM.ts:68:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at TalkCommand.handleQuest (/bin/src/SlashCommands/Commands/Location/Talk.ts:742:4)
    at TalkCommand.run (/bin/src/SlashCommands/Commands/Location/Talk.ts:973:18)
    at originalCommandRunner (/bin/src/Bot.ts:121:18)
```

### 🎲 DRPG version

v4.18.49

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by Sven65** [comment] 2024-11-13 12:12
Duplicate of #1383.

**Closed as completed by Sven65** 2024-11-13 12:12 UTC
